[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "image-measurement-tool"
version = "0.1.0"
description = "A GUI tool for measuring objects in images, using relative sizes of objects with known dimensions."
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]

dependencies = [
    "opencv-python>=4.5.0",
    "numpy>=1.21.0",
    "typed-argparse~=0.3.1",
]


[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D203",
    "D212",

    "T201", # Allow prints, for now.
]
